
title: Lekan's blog
email: lexilighty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  To discover and understand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lakehanne.gihub.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: patmeansnoble
github_username:  lakehanne
timezone:         America/Chicago
quora_username:   Olalekan-Ogunmolu
# defaults:
#   scope:
#     path: "assets/img"
#   values:
#     image: true
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  # - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
paginate: 5
