# Site settings
title: Olalekan Ogunmolu
email: lexilighty@gmail.com
description: "To Discover and Understand."
#  "Towards an autonomous future."
baseurl: ""
url: "lakehanne.github.io"
twitter_username: patmeansnoble
github_username: lakehanne
blogspot_username: fancylittlerobots
timezone: America/Chicago
quora_username: Olalekan-Ogunmolu
# gems:
#   - jekyll-feed
markdown: redcarpet
highlighter: pygments
permalink: pretty
#markdown: rdiscount
