
title:            Lekan Ogunmolu
locale:           en_US
email:            patlekno@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  To discover and understand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: heartunderknife
github_username:  lakehanne
timezone:         America/Chicago
quora_username:   Olalekan-Ogunmolu
sass:
  sass_dir: _sass
  style: compressed
defaults:
  - scope:
      path: "_quotes/quote_files"
    values:
      static: "true"
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  #- jekyll-coffeescript
  - jekyll-watch
  #- jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock
paginate: 2
paginate_path: "/blog/page:num/"
