# Site settings
title: Olalekan Ogunmolu's blog
email: 
description: "Towards an autonomous future."
baseurl: ""
url: "http://fancylittlerobots.blogspot.com"
twitter_username: patmeansnoble
github_username: lakehanne
blogspot: fancylittlerobots
timezone: America/Chicago
#collections: conferences journal articles computer vision natural robotics
# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
#markdown: rdiscount