# Site settings
title: Olalekan Ogunmolu's blog
email: 
description: "Towards an autonomous future."
baseurl: ""
url: "http://lakehanne.github.io"
twitter_username: patmeansnoble
github_username: lakehanne
blogspot_username: fancylittlerobots
timezone: America/Chicago
  gems:
    - jekyll-redirect-from
markdown: redcarpet
highlighter: pygments
permalink: pretty
#markdown: rdiscount