# Site settings
title: Olalekan Ogunmolu
email: 
description: "Towards an autonomous future."
baseurl: ""
url: "www.scriptedonchips.com"
twitter_username: patmeansnoble
github_username: lakehanne
blogspot_username: fancylittlerobots
timezone: America/Chicago
gems:
    - jekyll-redirect-from
markdown: redcarpet
highlighter: pygments
permalink: pretty
#markdown: rdiscount